{
  flake.modules.homeManager.common-packages = {pkgs, ...}: {
    home.packages = with pkgs; [
      neovim
      unzip
      fzf
      ripgrep
      fd
      g-ls
      tmuxinator
      delta
      cargo
      rustc
      zoxide
      fastfetch
      gcc
      jq
      luajitPackages.luarocks_bootstrap
      lazygit
      rtk
      nix-search-cli
      aerc
      gnumake
      nodejs_26
      opencode
      kitty
    ];
  };
}
